# Basic
title: KeJia Yin
subtitle: 
welcome_message: Welcome to my personal homepage
description: Now a senior student in Bejing Institute of Technology(BIT)
creator: <a href="http://yinkejia.github.io">@KeJia Yin</a>

url: "https://github.com/yinkejia/yinkejia.github.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: ABOUT ME, description: My Projects, url: 'https://yinkejia.github.io/2016/02/sample-post/'}
    - {title: ACADEMIC, description: My Projects, url: 'https://yinkejia.github.io/2021/08/ACADEMIC-PERFORMANCE/'}
    - {title: RESEARCH, description: My Projects, url: 'https://yinkejia.github.io/2021/08/RESEARCH-EXPERIENCE/'}
    - {title: SKILLS, description: My Projects, url: 'https://yinkejia.github.io/2021/08/AWARDS-&-LANGUAGES-&-SKILLS/'}
    
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: onevcat
    github: onevcat
    twitter: onevcat
    gplus: 107108267983477358170
    mail: onev@onevcat.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
